# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['pull_counter']},
        ),
        migrations.AddField(
            model_name='comic',
            name='pull_counter',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
