# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170909_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
