# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170909_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='weekly_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
