# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170909_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='cover_url',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='comic',
            name='price',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='comic',
            name='publisher',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='comic',
            name='title',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
